"""fix models1

Revision ID: 9f1f334c0fe3
Revises: 57de6c033255
Create Date: 2024-05-19 17:10:48.648320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f1f334c0fe3'
down_revision: Union[str, None] = '57de6c033255'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat', sa.Column('language', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat', 'language')
    # ### end Alembic commands ###
