"""fix models

Revision ID: edf0019ea105
Revises: 98e07d3e4077
Create Date: 2024-05-19 16:51:05.090139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edf0019ea105'
down_revision: Union[str, None] = '98e07d3e4077'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat', sa.Column('first_name', sa.String(), nullable=True))
    op.drop_column('chat', 'customer_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat', sa.Column('customer_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('chat', 'first_name')
    # ### end Alembic commands ###
