"""fix models1

Revision ID: f018819c66b7
Revises: a54288cda668
Create Date: 2024-05-20 15:26:45.996320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f018819c66b7'
down_revision: Union[str, None] = 'a54288cda668'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'field')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('field', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
